import enum

class Gender(enum.Enum):
    Male = 2
    Female = 1


class Voice:

    def __init__(self, name: str, gender: Gender, lang: str, voice_file: str):
        self.voice_file = voice_file
        self.lang = lang
        self.gender = gender
        self.name = name


class Voices:


    @staticmethod
    def load():
        # Ah, just like the good old pory days
        # Really brings me back

        voices = []
        voices.append(Voice("Mehdi", Gender.Male, "ar_sa", "ar_sa_hd_mehdi_22k_lf.bvcu"))
        voices.append(Voice("Nizar", Gender.Male, "ar_sa", "ar_sa_hd_nizar_22k_lf.bvcu"))
        voices.append(Voice("Salma", Gender.Female, "ar_sa", "ar_sa_hd_salma_22k_lf.bvcu"))
        voices.append(Voice("Leila", Gender.Female, "ar_sa", "ar_sa_hd_leila_22k_lf.bvcu"))
        voices.append(Voice("Laia", Gender.Female, "ca_es", "ca_es_hd_laia_22k_lf.bvcu"))
        voices.append(Voice("Eliska", Gender.Female, "cs_cz", "czc_hd_eliska_22k_lf.bvcu"))
        voices.append(Voice("Mette", Gender.Female, "da_dk", "dad_hd_mette_22k_lf.bvcu"))
        voices.append(Voice("Rasmus", Gender.Male, "da_dk", "dad_hd_rasmus_22k_lf.bvcu"))
        voices.append(Voice("Lea", Gender.Female, "de_de", "ged_lea_22k_ns.bvcu"))
        voices.append(Voice("ClaudiaSmile", Gender.Female, "de_de", "ged_hd_claudiasmile_22k_lf.bvcu"))
        voices.append(Voice("Jonas", Gender.Male, "de_de", "ged_jonas_22k_ns.bvcu"))
        voices.append(Voice("Andreas", Gender.Male, "de_de", "ged_hd_andreas_22k_lf.bvcu"))
        voices.append(Voice("Claudia", Gender.Female, "de_de", "ged_hd_claudia_22k_lf.bvcu"))
        voices.append(Voice("Sarah", Gender.Female, "de_de", "ged_hd_sarah_22k_lf.bvcu"))
        voices.append(Voice("Julia", Gender.Female, "de_de", "ged_hd_julia_22k_lf.bvcu"))
        voices.append(Voice("Klaus", Gender.Male, "de_de", "ged_hd_klaus_22k_lf.bvcu"))
        voices.append(Voice("Dimitris", Gender.Male, "el_gr", "grg_hd_dimitris_22k_lf.bvcu"))
        voices.append(Voice("DimitrisSad", Gender.Male, "el_gr", "grg_dimitrissad_22k_ns.bvcu"))
        voices.append(Voice("DimitrisHappy", Gender.Male, "el_gr", "grg_dimitrishappy_22k_ns.bvcu"))
        voices.append(Voice("Lisa", Gender.Female, "en_au", "en_au_hd_lisa_22k_lf.bvcu"))
        voices.append(Voice("Liam", Gender.Male, "en_au", "en_au_liam_22k_ns.bvcu"))
        voices.append(Voice("Olivia", Gender.Female, "en_au", "en_au_olivia_22k_ns.bvcu"))
        voices.append(Voice("Tyler", Gender.Male, "en_au", "en_au_hd_tyler_22k_lf.bvcu"))
        voices.append(Voice("Rachel", Gender.Male, "en_gb", "eng_hd_rachel_22k_lf.bvcu"))
        voices.append(Voice("Graham", Gender.Male, "en_gb", "eng_hd_graham_22k_lf.bvcu"))
        voices.append(Voice("Rosie", Gender.Female, "en_gb", "eng_rosie_22k_ns.bvcu"))
        voices.append(Voice("Peter", Gender.Male, "en_gb", "eng_hd_peter_22k_lf.bvcu"))
        voices.append(Voice("Harry", Gender.Male, "en_gb", "eng_harry_22k_ns.bvcu"))
        voices.append(Voice("QueenElizabeth", Gender.Female, "en_gb", "eng_queenelizabeth_22k_ns.bvcu"))
        voices.append(Voice("Lucy", Gender.Female, "en_gb", "eng_hd_lucy_22k_lf.bvcu"))
        voices.append(Voice("PeterSad", Gender.Male, "en_gb", "eng_petersad_22k_ns.bvcu"))
        voices.append(Voice("PeterHappy", Gender.Male, "en_gb", "eng_peterhappy_22k_ns.bvcu"))
        voices.append(Voice("Deepa", Gender.Female, "en_in", "en_in_hd_deepa_22k_lf.bvcu"))
        voices.append(Voice("Rhona", Gender.Female, "gd_GB", "en_sct_hd_rhona_22k_lf.bvcu"))
        voices.append(Voice("Rod", Gender.Male, "en_us", "enu_hd_rod_22k_lf.bvcu"))
        voices.append(Voice("WillOldMan", Gender.Male, "en_us", "enu_willoldman_22k_ns.bvcu"))
        voices.append(Voice("Tracy", Gender.Female, "en_us", "enu_hd_tracy_22k_lf.bvcu"))
        voices.append(Voice("Kenny", Gender.Male, "en_us", "enu_hd_kenny_22k_lf.bvcu"))
        voices.append(Voice("WillBadGuy", Gender.Male, "en_us", "enu_willbadguy_22k_ns.bvcu"))
        voices.append(Voice("Micah", Gender.Male, "en_us", "enu_micah_22k_ns.bvcu"))
        voices.append(Voice("Ella", Gender.Female, "en_us", "enu_ella_22k_ns.bvcu"))
        voices.append(Voice("Saul", Gender.Male, "en_us", "enu_saul_22k_ns.bvcu"))
        voices.append(Voice("Valeria US", Gender.Female, "en_us", "enu_valeriaenglish_22k_ns.bvcu"))
        voices.append(Voice("Laura", Gender.Female, "en_us", "enu_hd_laura_22k_lf.bvcu"))
        voices.append(Voice("WillLittleCreature", Gender.Male, "en_us", "enu_willlittlecreature_22k_ns.bvcu"))
        voices.append(Voice("Nelly", Gender.Female, "en_us", "enu_hd_nelly_22k_lf.bvcu"))
        voices.append(Voice("Emilio US", Gender.Male, "en_us", "enu_emilioenglish_22k_ns.bvcu"))
        voices.append(Voice("Will", Gender.Male, "en_us", "enu_hd_will_22k_lf.bvcu"))
        voices.append(Voice("WillUpClose", Gender.Male, "en_us", "enu_willupclose_22k_ns.bvcu"))
        voices.append(Voice("WillHappy", Gender.Male, "en_us", "enu_willhappy_22k_ns.bvcu"))
        voices.append(Voice("Sharon", Gender.Female, "en_us", "enu_hd_sharon_22k_lf.bvcu"))
        voices.append(Voice("Karen", Gender.Female, "en_us", "enu_karen_22k_ns.bvcu"))
        voices.append(Voice("WillSad", Gender.Male, "en_us", "enu_willsad_22k_ns.bvcu"))
        voices.append(Voice("Josh", Gender.Male, "en_us", "enu_josh_22k_ns.bvcu"))
        voices.append(Voice("WillFromAfar", Gender.Male, "en_us", "enu_willfromafar_22k_ns.bvcu"))
        voices.append(Voice("Ryan", Gender.Male, "en_us", "enu_hd_ryan_22k_lf.bvcu"))
        voices.append(Voice("Scott", Gender.Male, "en_us", "enu_scott_22k_ns.bvcu"))
        voices.append(Voice("Antonio", Gender.Male, "es_es", "sps_hd_antonio_22k_lf.bvcu"))
        voices.append(Voice("Maria", Gender.Female, "es_es", "sps_hd_maria_22k_lf.bvcu"))
        voices.append(Voice("Ines", Gender.Female, "es_es", "sps_hd_ines_22k_lf.bvcu"))
        voices.append(Voice("Valeria Spanish", Gender.Female, "es_us", "spu_valeria_22k_ns.bvcu"))
        voices.append(Voice("Emilio Spanish", Gender.Male, "es_us", "spu_emilio_22k_ns.bvcu"))
        voices.append(Voice("Rosa", Gender.Female, "es_us", "spu_hd_rosa_22k_lf.bvcu"))
        voices.append(Voice("Rodrigo", Gender.Male, "es_us", "spu_hd_rodrigo_22k_lf.bvcu"))
        voices.append(Voice("Sanna", Gender.Female, "fi_fi", "fif_hd_sanna_22k_lf.bvcu"))
        voices.append(Voice("Hanus", Gender.Female, "fo_fo", "fo_fo_hanus_22k_ns.bvcu"))
        voices.append(Voice("Hanna", Gender.Female, "fo_fo", "fo_fo_hanna_22k_ns.bvcu"))
        voices.append(Voice("Louise", Gender.Female, "fr_ca", "frc_hd_louise_22k_lf.bvcu"))
        voices.append(Voice("Manon", Gender.Female, "fr_fr", "frf_hd_manon_22k_lf.bvcu"))
        voices.append(Voice("Alice", Gender.Female, "fr_fr", "frf_hd_alice_22k_lf.bvcu"))
        voices.append(Voice("AntoineHappy", Gender.Male, "fr_fr", "frf_antoinehappy_22k_ns.bvcu"))
        voices.append(Voice("MargauxHappy", Gender.Female, "fr_fr", "frf_margauxhappy_22k_ns.bvcu"))
        voices.append(Voice("Julie", Gender.Female, "fr_fr", "frf_hd_julie_22k_lf.bvcu"))
        voices.append(Voice("Robot", Gender.Male, "fr_fr", "frf_robot_22k_ns.bvcu"))
        voices.append(Voice("AntoineFromAfar", Gender.Male, "fr_fr", "frf_antoinefromafar_22k_ns.bvcu"))
        voices.append(Voice("MargauxHappy", Gender.Female, "fr_fr", "frf_margauxhappy_22k_ns.bvcu"))
        voices.append(Voice("Bruno", Gender.Male, "fr_fr", "frf_hd_bruno_22k_lf.bvcu"))
        voices.append(Voice("Margaux", Gender.Female, "fr_fr", "frf_hd_margaux_22k_lf.bvcu"))
        voices.append(Voice("Anais", Gender.Female, "fr_fr", "frf_hd_anais_22k_lf.bvcu"))
        voices.append(Voice("Valentin", Gender.Male, "fr_fr", "frf_valentin_22k_ns.bvcu"))
        voices.append(Voice("AntoineUpClose", Gender.Male, "fr_fr", "frf_antoineupclose_22k_ns.bvcu"))
        voices.append(Voice("Claire", Gender.Female, "fr_fr", "frf_hd_claire_22k_lf.bvcu"))
        voices.append(Voice("Antoine", Gender.Male, "fr_fr", "frf_hd_antoine_22k_lf.bvcu"))
        voices.append(Voice("Elise", Gender.Female, "fr_fr", "frf_elise_22k_ns.bvcu"))
        voices.append(Voice("AntoineSad", Gender.Male, "fr_fr", "frf_antoinesad_22k_ns.bvcu"))
        voices.append(Voice("MargauxSad", Gender.Male, "fr_fr", "frf_margauxsad_22k_ns.bvcu"))
        voices.append(Voice("Kal", Gender.Male, "swe", "gb_se_hd_kal_22k_lf.bvcu"))
        voices.append(Voice("Aurora", Gender.Female, "it_it", "iti_aurora_22k_ns.bvcu"))
        voices.append(Voice("Fabiana", Gender.Female, "it_it", "iti_hd_fabiana_22k_lf.bvcu"))
        voices.append(Voice("Alessio", Gender.Male, "it_it", "iti_alessio_22k_ns.bvcu"))
        voices.append(Voice("Vittorio", Gender.Male, "it_it", "iti_hd_vittorio_22k_lf.bvcu"))
        voices.append(Voice("Chiara", Gender.Female, "it_it", "iti_hd_chiara_22k_lf.bvcu"))
        voices.append(Voice("Sakura", Gender.Female, "ja_jp", "ja_jp_hd_sakura_22k_lf.bvcu"))
        voices.append(Voice("Minji", Gender.Female, "ko_kr", "ko_kr_hd_minji_22k_lf.bvcu"))
        voices.append(Voice("Zoe", Gender.Female, "nl_be", "dub_hd_zoe_22k_lf.bvcu"))
        voices.append(Voice("JeroenSad", Gender.Male, "nl_be", "dub_jeroensad_22k_ns.bvcu"))
        voices.append(Voice("Sofie", Gender.Female, "nl_be", "dub_hd_sofie_22k_lf.bvcu"))
        voices.append(Voice("JeroenHappy", Gender.Male, "nl_be", "dub_jeroenhappy_22k_ns.bvcu"))
        voices.append(Voice("Jeroen", Gender.Male, "nl_be", "dub_hd_jeroen_22k_lf.bvcu"))
        voices.append(Voice("Jasmijn", Gender.Male, "nl_nl", "dun_hd_jasmijn_22k_lf.bvcu"))
        voices.append(Voice("Max", Gender.Male, "nl_nl", "dun_hd_max_22k_lf.bvcu"))
        voices.append(Voice("Daan", Gender.Male, "nl_nl", "dun_hd_daan_22k_lf.bvcu"))
        voices.append(Voice("Femke", Gender.Female, "nl_nl", "dun_hd_femke_22k_lf.bvcu"))
        voices.append(Voice("Elias", Gender.Male, "no", "non_elias_22k_ns.bvcu"))
        voices.append(Voice("Kari", Gender.Female, "no", "non_hd_kari_22k_lf.bvcu"))
        voices.append(Voice("Emilie", Gender.Female, "no", "non_emilie_22k_ns.bvcu"))
        voices.append(Voice("Bente", Gender.Female, "no", "non_hd_bente_22k_lf.bvcu"))
        voices.append(Voice("Olav", Gender.Male, "no", "non_hd_olav_22k_lf.bvcu"))
        voices.append(Voice("Ania", Gender.Female, "pl_pl", "pop_hd_ania_22k_lf.bvcu"))
        voices.append(Voice("Marcia", Gender.Female, "pt_br", "pob_hd_marcia_22k_lf.bvcu"))
        voices.append(Voice("Celia", Gender.Female, "pt_pt", "poe_hd_celia_22k_lf.bvcu"))
        voices.append(Voice("Alyona", Gender.Female, "ru_ru", "rur_hd_alyona_22k_lf.bvcu"))
        voices.append(Voice("Mia", Gender.Female, "swe", "sc_se_hd_mia_22k_lf.bvcu"))
        voices.append(Voice("Samuel", Gender.Female, "sv_fi", "sv_fi_hd_samuel_22k_lf.bvcu"))
        voices.append(Voice("Elin", Gender.Female, "sv_se", "sws_hd_elin_22k_lf.bvcu"))
        voices.append(Voice("Freja", Gender.Female, "sv_se", "sws_freja_22k_ns.bvcu"))
        voices.append(Voice("Erik", Gender.Male, "sv_se", "sws_hd_erik_22k_lf.bvcu"))
        voices.append(Voice("Filip", Gender.Male, "sv_se", "sws_filip_22k_ns.bvcu"))
        voices.append(Voice("Emma", Gender.Female, "sv_se", "sws_hd_emma_22k_lf.bvcu"))
        voices.append(Voice("Emil", Gender.Male, "sv_se", "sws_hd_emil_22k_lf.bvcu"))
        voices.append(Voice("Ipek", Gender.Female, "tr_tr", "tut_hd_ipek_22k_lf.bvcu"))
        voices.append(Voice("Lulu", Gender.Female, "zh_cn", "zh_cn_hd_lulu_22k_lf.bvcu"))

        return voices
